name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    tags: 
      - v*

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Tests
        working-directory: ./app
        run: |
          yarn install 
          yarn test

  build-push:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: Jest
    steps:
    - uses: actions/checkout@v4
    - name: login to docker hub
      uses: docker/login-action@v3
      with: 
        username: ${{secrets.DOCKER_USERNAME }}
        password: ${{secrets.DOCKER_PASSWORD }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: ./app
        push: true
        tags: ${{secrets.DOCKER_USERNAME }}/to-do-app:latest
        
  deploy: 
    runs-on: self-hosted
    needs: [Jest, build-push]
    steps:
    - name: Pull Docker Image
      run: docker pull ${{secrets.DOCKER_USERNAME }}/to-do-app:latest
    - name: Stop instances of image
      run: docker stop app
    - name: Run Docker Container
      run: docker run -d -p 3000:3000 --name app ${{secrets.DOCKER_USERNAME }}/to-do-app:latest
      
  
